### ISSUE TITLE
Initial configuration without XML files.

### ISSUE THREAD

**Issue by itunc** [camunda-community-hub/camunda-bpm-junit5#10]

**Comment by itunc** [comment]
The current setup needs camunda.cfg.xml to be defined and properly set. It's not suited to Springboot Camunda distros, where one should create and properly set the *.yml / *.properties Files to this extra camunda.cfg.xml. 
There is a related issue but I think we need more than just an example. In the current state, the extension is not really usable for Camunda teams working with SpringBoot.

**Comment by ingorichtsmeier** [comment]
Hi @itunc,

I've created an example to test a process automated with the camunda-bpm-spring-boot-starter and JUnit 5 here: https://github.com/camunda-community-hub/camunda-bpm-junit5/tree/spring-boot-example/examples/example-spring-boot-testing. 

This extension is not required here.

What do you think about this example? 

Do you miss anything here?

**Comment by itunc** [comment]
Hi @ingorichtsmeier , thanks first of all for taking the time and preparing this example. I could unfortunately only take the time to check your code. Maybe I should have give more information about our testing state, anyway we write the process tests where the spring context ist needed (longer processes with interactions with subprocesses) anyway very similar to your example already. 
Due to timing & dirty context issues, we wanted to write the test code for smaller process interactions without spring context with JUnit5 using your extension, which would give us the possiblity to use RuntimeService & co. out of the box. This seems unfortunately not to be the case without providing an appropriate XML-configuration file.

**Comment by ingorichtsmeier** [comment]
Hi @itunc, check the example about registering a process engine for your tests: https://github.com/camunda-community-hub/camunda-bpm-junit5/blob/use_own_process_engine/examples/engine-camunda-bpm-assert/src/test/java/org/camunda/bpm/unittest/engine/UseProcessEngineTest.java

It's on a new branch.

Does this example match your requirements?

**Comment by ingorichtsmeier** [comment]
See https://github.com/camunda-community-hub/camunda-bpm-junit5/issues/7.
