### ISSUE TITLE
JUnit5 testing for Spring Boot application and custom database schema

### ISSUE THREAD

**Issue by TobiasHerb** [camunda-community-hub/camunda-bpm-junit5#12]
Hi, 

I would like to know how to use JUnit5 testing library in combination with Spring Boot application (camunda-bpm-spring-boot-starter) and custom database schema. Do I need to create a 'camunda.cfg.xml' in '/test/resources'? And if so, how do I set the 'table-prefix' in this configuration?

Cheers,
Tobi

**Comment by ingorichtsmeier** [comment]
Hi @TobiasHerb, to test the camunda-spring-boot-starter with junit5, this extension is not required. 

I've created this example how to test a process with the spring-boot and junit5: https://github.com/camunda-community-hub/camunda-bpm-junit5/tree/spring-boot-example/examples/example-spring-boot-testing.

It may not be the only possible way, but a working example. Spring magic helps to inject the `runtimeService` into the test and `camunda-bpm-assert` can be used to write comprehensive tests.

Does it answer your question?

**Comment by TobiasHerb** [comment]
Works. Thanks.
