### ISSUE TITLE
use correct builder pattern

### ISSUE THREAD

**Issue by jangalinski** [camunda-community-hub/camunda-bpm-junit5#2]
the extension configuration should not be altered after the extension was created ... so I would vote against setters for config, resources, ...

You already provided a `builder()` method. Shouldn't this return a ProcessEngineExtensionBuilder then, that is used to configure and create the extension instance?

**Comment by jangalinski** [comment]
Note: as this is already released, removing the setters will be a breaking change ... but maybe since this extension is not used by many projects, it is still time to just do it.

**Comment by ingorichtsmeier** [comment]
Hi @jangalinski,

> the extension configuration should not be altered after the extension was created

you are right.

I've created a branch for this: https://github.com/camunda/camunda-bpm-junit5/commit/8c870a77414f06de680f0fc8d3c4ffd5d4c8a2b2

If you agree, I could publish this as version 1.0.1. Or would you like a different version (2.0.0) as it is a breaking change?

What do you think?

**Comment by jangalinski** [comment]
As I said ... it _would_ be an incompatible version change ... but I don't think that. (considerung the low amount of users) that this is worth a 2.0.0 ... I would have gone with 1.1.0, but 1.0.1 is ok for me as well.

BTW: When you set the next DEV version, use the patch version, not the minor version ... now it could be that there are 1.1.0-SNAPSHOT releases out in the open when you release 1.0.1 ... 
Might be an indicator to use 1.1.0 for the release and 1.1.1-SNAPSHOT for the next dev

**Comment by jangalinski** [comment]
And: the configuration resource and the process engine can still be changed on the extension object ... I meant making them immutable in the extension and use the builder to set them in the constructor of the extensuin.

**Comment by ingorichtsmeier** [comment]
released as 1.0.1
