### ISSUE TITLE
new release for maven central

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/camunda-bpm-junit5#29]
Hi Devrel team, 

could you please push 1.1.0 to maven central?

Thank you, Ingo

**Comment by ingorichtsmeier** [comment]
@camunda-community-hub/devrel

**Comment by celanthe** [comment]
Hi @ingorichtsmeier! I've gone ahead and release this to Maven central. You should see it available within the next few hours! :)

**Comment by akeller** [comment]
@ingorichtsmeier do you need any further assistance?
