### ISSUE TITLE
ProcessEngineExtension should implement ProcessEngineServices

### ISSUE THREAD

**Issue by jangalinski** [camunda-community-hub/camunda-bpm-junit5#3]
With the junit4 rule, I am used to get the service instances directly from the rule, because it implements the ProcessEngineServices interface.

I would like the extension to behave the same, so this

    RuntimeService runtimeService = extension.getProcessEngine().getRuntimeService(); 

becomes:

    RuntimeService runtimeService = extension.getRuntimeService();

**Comment by ingorichtsmeier** [comment]
Hi @jangalinski,

I left these services out of the extension as I always use it in combination with [camunda-bpm-assert](https://github.com/camunda/camunda-bpm-assert/). 

The assert extensions provides this services even better as static methods. 

What is your usecase where you miss the service shortcuts?

**Comment by jangalinski** [comment]
Main reason: symetry ... the rule has this, so the extension should too ... 
But I also use this regullary in my tests ... and It won't hurt not to assume that every junit5 user also uses assertj.

**Comment by ThorbenLindhauer** [comment]
This request has been implemented along with the move to the core product codebase: https://github.com/camunda/camunda-bpm-platform/blob/master/test-utils/junit5-extension/src/main/java/org/camunda/bpm/engine/test/junit5/ProcessEngineExtension.java
