### ISSUE TITLE
ProcessEngineExtension should inject ProcessEngine in Superclasses

### ISSUE THREAD

**Issue by criew** [camunda-community-hub/camunda-bpm-junit5#6]
ProcessEngineExtension::109 does not consider the class hierarchy for injection. That would be very nice in examples like the following:

```
@ExtendWith(ProcessEngineExtension.class)
public class ProcessEngineTestBase {
    protected ProcessEngine processEngine;

    @BeforeEach
    void setupBpmnAssert() {
        BpmnAwareTests.init(processEngine);
    }

    // some more convenience
}

public class MyTest extends ProcessEngineTestBase {
    @Test
    void test() {
           assertNotNull(processEngine); // NPE
}
```

**Comment by criew** [comment]
@ingorichtsmeier would it be possible to include superclass - injection in the next release?

**Comment by ThorbenLindhauer** [comment]
Hi @criew,

We have moved the codebase of this extension into the core product at: https://github.com/camunda/camunda-bpm-platform/tree/master/test-utils/junit5-extension.

With that, we are no longer using this repository, including its issues. If your request is still relevant, please consider raising a ticket in the CAM JIRA issue tracker: https://jira.camunda.com/browse/CAM.

Cheers,
Thorben
